# Generated by Django 4.1.2 on 2022-11-13 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_slug', models.SlugField(blank=True, null=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('subject_subname', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_btn_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255)),
                ('site_intro', models.ImageField(blank=True, null=True, upload_to='site_pic/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Virtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_title', models.CharField(max_length=255)),
                ('virtual_url', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, choices=[('Kafedra mudiri', 'Kafedra mudiri'), ('Dotsent', 'Dotsent'), ("Katta o'qituvchi", "Katta o'qituvchi"), ("O'qituvchi", "O'qituvchi"), ('Laborant', 'Laborant')], max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('Asosiy shtat', 'Asosiy shtat'), ("Ichki o'rindosh", "Ichki o'rindosh"), ("Tashqi o'rindosh", "Tashqi o'rindosh")], max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('subjects', models.ManyToManyField(to='teachers.subject')),
                ('teacher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_title', models.CharField(max_length=255)),
                ('presentation_pic', models.ImageField(blank=True, null=True, upload_to='presentation/')),
                ('presentation_file', models.FileField(upload_to='presentation/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=255)),
                ('portfolio_authors', models.TextField()),
                ('portfolio_address', models.TextField()),
                ('portfolio_date', models.DateField()),
                ('portfolio_description', models.TextField(blank=True, null=True)),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='portfolio_files/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.portfoliocategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maruza_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('maruza_title', models.CharField(max_length=255)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('maruza_file', models.FileField(upload_to='maruzalar/file/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glossary_slug', models.SlugField(blank=True, null=True)),
                ('glossary_title', models.CharField(max_length=255)),
                ('glossary_body', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_pic', models.ImageField(upload_to='resourse/book/')),
                ('book_file', models.FileField(upload_to='resourse/book/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AmaliyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practis_name', models.CharField(max_length=255)),
                ('practis_slug', models.SlugField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Amaliy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practis_id', models.IntegerField(blank=True, null=True)),
                ('question_slug', models.SlugField()),
                ('question_title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('solusion', models.TextField(blank=True, null=True)),
                ('checking', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('practis_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.amaliytheme')),
            ],
        ),
    ]
