# Generated by Django 4.1.2 on 2022-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amaliy',
            name='practis_id',
        ),
        migrations.AddField(
            model_name='amaliytheme',
            name='practis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
