# Generated by Django 4.1.2 on 2022-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_amaliy_practis_id_amaliytheme_practis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_file_1',
            field=models.FileField(blank=True, null=True, upload_to='subject_files/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_file_2',
            field=models.FileField(blank=True, null=True, upload_to='subject_files/'),
        ),
    ]
