# Generated by Django 4.1.2 on 2022-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_subject_subject_file_1_subject_subject_file_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timer',
            field=models.IntegerField(default=60),
        ),
    ]
