# Generated by Django 4.1.2 on 2022-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_test_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_files/'),
        ),
    ]
