# Generated by Django 4.1.2 on 2022-11-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_portfoliocategory_portfolio_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_category',
            field=models.CharField(blank=True, choices=[('Axborot tizimlari va texnalogiyalari', 'Axborot tizimlari va texnalogiyalari'), ('Informatika va axborot tizimlari', 'Informatika va axborot tizimlari'), ('-', '-')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_file_3',
            field=models.FileField(blank=True, null=True, upload_to='subject_files/', verbose_name='Fan rejasi'),
        ),
    ]
