# Generated by Django 4.1.2 on 2022-11-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_subject_subject_category_subject_subject_file_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='maruza',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='maruza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.maruza'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.subjectcategory'),
        ),
    ]
