# Generated by Django 4.1.2 on 2022-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_subjectcategory_remove_maruza_video_video_maruza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_file_3',
            field=models.FileField(upload_to='subject_files/', verbose_name='Fan rejasi'),
        ),
    ]
