# Generated by Django 4.1.2 on 2022-11-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_contactmessage_alter_portfolio_portfolio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
