# Generated by Django 4.1.2 on 2022-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_contactmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='number',
            field=models.CharField(default='969696969', max_length=255),
            preserve_default=False,
        ),
    ]
