# Generated by Django 4.1.2 on 2022-11-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_file',
        ),
    ]
