# Generated by Django 4.1.2 on 2022-11-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_remove_portfolio_portfolio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_img',
            new_name='img',
        ),
    ]
