# Generated by Django 4.1.2 on 2022-11-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_rename_portfolio_img_portfolio_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_btn_color',
        ),
    ]
