# Generated by Django 4.1.2 on 2022-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0018_remove_subject_subject_btn_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="facebook",
            field=models.CharField(default="/", max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="instagram",
            field=models.CharField(default="/", max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kafedra mudiri", "Kafedra mudiri"),
                    ("Dotsent", "Dotsent"),
                    ("Professor", "Professor"),
                    ("Katta o'qituvchi", "Katta o'qituvchi"),
                    ("O'qituvchi", "O'qituvchi"),
                    ("Laborant", "Laborant"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="telegram",
            field=models.CharField(default="/", max_length=255),
        ),
    ]
