# Generated by Django 4.1.2 on 2022-11-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0019_alter_teacher_facebook_alter_teacher_instagram_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amaliy",
            name="question_slug",
            field=models.CharField(max_length=255),
        ),
    ]
