# Generated by Django 4.1.2 on 2022-11-21 06:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0020_alter_amaliy_question_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="question",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
