# Generated by Django 4.1.2 on 2024-01-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0021_alter_test_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glossary",
            options={"ordering": ["glossary_title"]},
        ),
    ]
