# Generated by Django 4.1.2 on 2024-01-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0022_alter_glossary_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="portfolio_url",
            field=models.CharField(default="/", max_length=255),
        ),
    ]
