# Generated by Django 4.1.2 on 2024-01-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teachers", "0023_teacher_portfolio_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="portfolio_url",
            new_name="e_dars_url",
        ),
    ]
