# Generated by Django 4.1.2 on 2022-11-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='posts_img/')),
                ('body', models.FileField(upload_to='posts/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('post_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('ball', models.IntegerField()),
                ('timer', models.IntegerField(blank=True, default=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=255)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.FileField(upload_to='maruzalar/')),
                ('scince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_dars.scince')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='resource_img/')),
                ('file', models.FileField(blank=True, null=True, upload_to='resource_file/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_dars.resourcecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PractisTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practis_id', models.IntegerField(blank=True, null=True)),
                ('practis_name', models.CharField(max_length=255)),
                ('practis_slug', models.SlugField(max_length=255)),
                ('scince', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_dars.scince')),
            ],
        ),
        migrations.CreateModel(
            name='Practis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.FileField(upload_to='lab/')),
                ('practis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_dars.practistheme')),
            ],
        ),
    ]
