# Generated by Django 4.1.2 on 2023-05-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("e_dars", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Glossary",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.RemoveField(
            model_name="practis",
            name="practis_name",
        ),
        migrations.RemoveField(
            model_name="practistheme",
            name="scince",
        ),
        migrations.DeleteModel(
            name="Quizes",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="theme",
            name="scince",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.DeleteModel(
            name="Practis",
        ),
        migrations.DeleteModel(
            name="PractisTheme",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="ResourceCategory",
        ),
        migrations.DeleteModel(
            name="Scince",
        ),
        migrations.DeleteModel(
            name="Theme",
        ),
    ]
