# Generated by Django 4.1.2 on 2023-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kafedra", "0002_alter_articleviewip_ip_articlegallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["created_date"]},
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
