# Generated by Django 4.1.2 on 2024-01-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kafedra", "0004_article_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_date"]},
        ),
    ]
